### ISSUE TITLE
vrp_env - build fail

### ISSUE THREAD

**Issue by Borek-Reich** [water-mirror/NeuLNS#11]
Hello,

when building vrp_env I encountered an error:
```
error[E0432]: unresolved import `syn::export`106: dict_derive, pyo3(build)                                                  
 --> /home/borek/.cargo/registry/src/github.com-1ecc6299db9ec823/dict_derive-0.2.0/src/from.rs:2:10
  |
2 | use syn::export::TokenStream2;
  |          ^^^^^^ could not find `export` in `syn`

error[E0433]: failed to resolve: could not find `export` in `syn`o3(build)                                                  
  --> /home/borek/.cargo/registry/src/github.com-1ecc6299db9ec823/dict_derive-0.2.0/src/from.rs:41:35
   |
41 | fn extraction_functions() -> syn::export::TokenStream2 {
   |                                   ^^^^^^ could not find `export` in `syn`
```

After some search (I do not program in RUST) I was able to get rid of this error by changing:
`use syn::export::TokenStream2;`
to:
`use proc_macro2::TokenStream as TokenStream2;`
in `dict_derive-0.2.0`.
After that, it built succesfully with a lot of warnings (included at the end of this post)...

But after that when I run:
`python train_model.py -n 99 -c 100`

It gives me following error:
```
Traceback (most recent call last):
  File "train_model.py", line 32, in <module>
    train(model,envs,1000,10,10,4)
  File "/home/borek/SNT/pyRefNeuLNS/src/cvrp/lib/utils_train.py", line 418, in train
    states,mean_cost = random_init(envs,pre_steps)
  File "/home/borek/SNT/pyRefNeuLNS/src/cvrp/lib/utils_train.py", line 403, in random_init
    nodes,edges = envs.reset()
  File "/home/borek/SNT/pyRefNeuLNS/src/cvrp/lib/utils_train.py", line 214, in reset
    rets = [ env.reset() for env in self.envs ]
  File "/home/borek/SNT/pyRefNeuLNS/src/cvrp/lib/utils_train.py", line 214, in <listcomp>
    rets = [ env.reset() for env in self.envs ]
  File "/home/borek/SNT/pyRefNeuLNS/src/cvrp/lib/utils_train.py", line 157, in reset
    self.env = vrp_env.Env(json.dumps(self.input))
AttributeError: module 'vrp_env' has no attribute 'Env'`
```

How do I fix this?
I am using: maturin 0.12.11, rustup 1.24.3, python 3.6, PyTorch 1.7.0 with corresponding packages.

Thank you in advance

(warnings encountered)
```
warning: unused import: `pyo3::types::*` 105/106: vrp_env                                                                             
 --> src/lib.rs:6:5
  |
6 | use pyo3::types::*;
  |     ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

    warning: unused import: `info`
 --> src/lib.rs:8:11
  |
8 | use log::{info, debug};
  |           ^^^^

Building
warning: unused imports: `max`, `min`> ] 105/106: vrp_env                                                                             
  --> src/lib.rs:13:16
   |
13 | use std::cmp::{min,max};
   |                ^^^ ^^^

    Building [=======================> ] 105/106: vrp_env                                                                             warning: unused import: `HashMap`
  --> src/lib.rs:14:17
   |
14 | use hashbrown::{HashMap};
   |                 ^^^^^^^

warning: unnecessary parentheses around function argument                                                                             
   --> src/lib.rs:600:12
    |
600 |         Ok((self.inner.step(jobs)))
    |            ^                     ^
    |
    = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
    |
600 -         Ok((self.inner.step(jobs)))
600 +         Ok(self.inner.step(jobs))
    | 

warning: unused import: `rayon::prelude` 105/106: vrp_env                                                                             
  --> src/lib.rs:17:5
   |
17 | use rayon::prelude::*;
   |     ^^^^^^^^^^^^^^

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:674:12
    |
674 | fn vrp_env(py: Python, m: &PyModule) -> PyResult<()> {
    |            ^^ help: if this is intentional, prefix it with an underscore: `_py`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `delta_t`==> ] 105/106: vrp_env                                                                             
  --> src/lib.rs:99:38
   |
99 |     fn calc_delta(&self,delta_d: f32,delta_t: f32,delta_w: f32) -> f32 {
   |                                      ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_delta_t`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:581:34
    |
581 |     fn __new__(obj: &PyRawObject,py: Python,input_str: &str) -> PyResult<()> {
    |                                  ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:591:22
    |
591 |     fn states(&self, py: Python) -> PyResult<Vec<Vec<State>>> {
    |                      ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:595:21
    |
595 |     fn tours(&self, py: Python) -> PyResult<Vec<Vec<usize>>> {
    |                     ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:599:23
    |
599 |     fn step(&mut self,py: Python,jobs: Vec<usize>) -> PyResult<()> {
    |                       ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:603:22
    |
603 |     fn absents(&self,py: Python) -> PyResult<Vec<usize>> {
    |                      ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:607:19
    |
607 |     fn cost(&self,py: Python) -> PyResult<f32> {
    |                   ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:624:34
    |
624 |     fn __new__(obj: &PyRawObject,py: Python,input_strs: Vec<String>) -> PyResult<()> {
    |                                  ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:635:22
    |
635 |     fn states(&self, py: Python) -> PyResult<Vec<Vec<Vec<State>>>> {
    |                      ^^ help: if this is intentional, prefix it with an underscore: `_py`

    Building [=======================> ] 105/106: vrp_env                                                                             warning: unused variable: `py`
   --> src/lib.rs:642:21
    |
642 |     fn tours(&self, py: Python) -> PyResult<Vec<Vec<Vec<usize>>>> {
    |                     ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:650:23
    |
650 |     fn step(&mut self,py: Python,jobs: Vec<Vec<usize>>) -> PyResult<()> {
    |                       ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:657:22
    |
657 |     fn absents(&self,py: Python) -> PyResult<Vec<Vec<usize>>> {
    |                      ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:664:19
    |
664 |     fn cost(&self,py: Python) -> PyResult<Vec<f32>> {
    |                   ^^ help: if this is intentional, prefix it with an underscore: `_py`


warning: 20 warnings emitted=========> ] 105/106: vrp_env                                                                             


    Finished release [optimized] target(s) in 5.93s
📦 Built wheel for CPython 3.6m to /home/borek/SNT/pyRefNeuLNS/src/cvrp/vrp_env/target/wheels/vrp_env-0.1.1-cp36-cp36m-manylinux_2_28_x86_64.whl
   Compiling pyo3 v0.8.5
   Compiling vrp_env v0.1.1 (/home/borek/SNT/pyRefNeuLNS/src/cvrp/vrp_env)
warning: unused import: `pyo3::types::*` 105/106: vrp_env                                                                             
 --> src/lib.rs:6:5
  |
6 | use pyo3::types::*;
  |     ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `info`=======> ] 105/106: vrp_env                                                                             
 --> src/lib.rs:8:11
  |
8 | use log::{info, debug};
  |           ^^^^

warning: unused imports: `max`, `min`> ] 105/106: vrp_env                                                                             
  --> src/lib.rs:13:16
   |
13 | use std::cmp::{min,max};
   |                ^^^ ^^^

warning: unused import: `HashMap`====> ] 105/106: vrp_env                                                                             
  --> src/lib.rs:14:17
   |
14 | use hashbrown::{HashMap};
   |                 ^^^^^^^

warning: unnecessary parentheses around function argument                                                                             
   --> src/lib.rs:600:12
    |
600 |         Ok((self.inner.step(jobs)))
    |            ^                     ^
    |
    = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
    |
600 -         Ok((self.inner.step(jobs)))
600 +         Ok(self.inner.step(jobs))
    | 

warning: unused import: `rayon::prelude` 105/106: vrp_env                                                                             
  --> src/lib.rs:17:5
   |
17 | use rayon::prelude::*;
   |     ^^^^^^^^^^^^^^

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:674:12
    |
674 | fn vrp_env(py: Python, m: &PyModule) -> PyResult<()> {
    |            ^^ help: if this is intentional, prefix it with an underscore: `_py`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `delta_t`==> ] 105/106: vrp_env                                                                             
  --> src/lib.rs:99:38
   |
99 |     fn calc_delta(&self,delta_d: f32,delta_t: f32,delta_w: f32) -> f32 {
   |                                      ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_delta_t`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:581:34
    |
581 |     fn __new__(obj: &PyRawObject,py: Python,input_str: &str) -> PyResult<()> {
    |                                  ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:591:22
    |
591 |     fn states(&self, py: Python) -> PyResult<Vec<Vec<State>>> {
    |                      ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:595:21
    |
595 |     fn tours(&self, py: Python) -> PyResult<Vec<Vec<usize>>> {
    |                     ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:599:23
    |
599 |     fn step(&mut self,py: Python,jobs: Vec<usize>) -> PyResult<()> {
    |                       ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:603:22
    |
603 |     fn absents(&self,py: Python) -> PyResult<Vec<usize>> {
    |                      ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:607:19
    |
607 |     fn cost(&self,py: Python) -> PyResult<f32> {
    |                   ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:624:34
    |
624 |     fn __new__(obj: &PyRawObject,py: Python,input_strs: Vec<String>) -> PyResult<()> {
    |                                  ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:635:22
    |
635 |     fn states(&self, py: Python) -> PyResult<Vec<Vec<Vec<State>>>> {
    |                      ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:642:21
    |
642 |     fn tours(&self, py: Python) -> PyResult<Vec<Vec<Vec<usize>>>> {
    |                     ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:650:23
    |
650 |     fn step(&mut self,py: Python,jobs: Vec<Vec<usize>>) -> PyResult<()> {
    |                       ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:657:22
    |
657 |     fn absents(&self,py: Python) -> PyResult<Vec<Vec<usize>>> {
    |                      ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: unused variable: `py`=======> ] 105/106: vrp_env                                                                             
   --> src/lib.rs:664:19
    |
664 |     fn cost(&self,py: Python) -> PyResult<Vec<f32>> {
    |                   ^^ help: if this is intentional, prefix it with an underscore: `_py`

warning: 20 warnings emitted=========> ] 105/106: vrp_env    
```

**Comment by binshaea** [comment]
I am having the same issue. 
Is this related to the version of syn that is specified in the Cargo.lock file ? 
![Capture1](https://github.com/water-mirror/NeuLNS/assets/138469614/609e500a-9382-4bc4-98a8-4d84f074955a)
