### ISSUE TITLE
cannot run train_model.py

### ISSUE THREAD

**Issue by davidkiller96** [water-mirror/NeuLNS#7]
Hello, I have some problem with running train_model.py

`Traceback (most recent call last):
  File "/content/NeuLNS/src/cvrp/train_model.py", line 9, in <module>
    from torch_geometric.data import Data,DataLoader
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/usr/local/lib/python3.6/dist-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/usr/local/lib/python3.6/dist-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/dist-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs`

I have no idea how to solve it, please give me some suggestion.
PS : some Information about my environment:
torch: 1.6.0+cu101
python : 3.6.9 (default, Jul 17 2020, 12:50:27) 
torch_geometric: 1.3.2
torch-sparse: 0.6.5
vip_env : 0.1.1
Thanks for your time!

**Comment by cburdea** [comment]
Hi, I have had this issue and the main problem was that the versions of all torch libraries were not aligned. In my case, I used the following commands: 

pip install torch==1.7.0
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
pip install torch-geometric==1.4.3

You may need to install other versions depending on your gpu
